[platformio]
src_dir = src
; src_dir = mp3
default_envs = debug

[env]
platform = espressif32@^6.12.0
framework = arduino
monitor_speed = 115200
check_tool = clangtidy
check_skip_packages = yes

[base]
board = esp32dev
build_flags = 
    ${env.build_flags}
	-std=c++14
	-mfix-esp32-psram-cache-issue
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_CALL_A7670_V1_0
monitor_filters = 
	default
	esp32_exception_decoder
lib_deps = 
	https://github.com/lewisxhe/TinyGSM-fork.git#3dd43c5638501a286a0b5713c716d26507f286e1
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^7.4.2

[async_web_deps]
lib_deps =
	ESP32Async/ESPAsyncWebServer@^3.8.1
	ESP32Async/AsyncTCP@^3.4.9

[webserial_deps]
lib_deps =
	${async_web_deps.lib_deps}
	ayushsharma82/WebSerial@^2.1.1

[base_ha]
extends = base
board_build.partitions = partitions.csv
build_flags = 
	${base.build_flags}
	-DHOME_ASSISTANT_INTEGRATION
lib_deps =
	${base.lib_deps}
	${async_web_deps.lib_deps}

[base_webserial]
extends = base
build_flags = 
	${base.build_flags}
	-DWEB_SERIAL
lib_deps =
	${base.lib_deps}
	${webserial_deps.lib_deps}

[base_debug]
build_type = debug
build_flags = 
	-O0
	-g3
	-fno-omit-frame-pointer
	-DDEBUG
	-DENABLE_INT_LOG_DEBUG
	-Wall
	-Wextra
	-Wno-format-truncation

[base_release]
build_flags = 
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-fno-exceptions
	-DNDEBUG

[env:debug]
extends = base, base_debug
build_flags = 
	${base.build_flags}
	${base_debug.build_flags}

[env:debugWebSerial]
extends = base_webserial, base_debug
build_flags = 
	${base_webserial.build_flags}
	${base_debug.build_flags}

[env:debugHA]
extends = base_ha, base_debug
build_flags = 
	${base_ha.build_flags}
	${base_debug.build_flags}

[env:debugWebSerialHA]
extends = base_ha, base_webserial, base_debug
build_flags = 
	${base_ha.build_flags}
	${base_webserial.build_flags}
	${base_debug.build_flags}

[env:release]
extends = base, base_release
build_flags = 
	${base.build_flags}
	${base_release.build_flags}

[env:releaseHA]
extends = base_ha, base_release
build_flags = 
	${base_ha.build_flags}
	${base_release.build_flags}

[env:releaseWebSerialHA]
extends = base_ha, base_webserial, base_release
build_flags = 
	${base_ha.build_flags}
	${base_webserial.build_flags}
	${base_release.build_flags}
	