[platformio]
src_dir = src
; src_dir = mp3
default_envs = debug

[env]
platform = espressif32@^6.11.0
framework = arduino
monitor_speed = 115200
check_tool = clangtidy
check_skip_packages = yes
board_build.partitions = partitions.csv

[base]
board = esp32dev
build_flags = 
    ${env.build_flags}
	-std=c++14
	-mfix-esp32-psram-cache-issue
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_CALL_A7670_V1_0
monitor_filters = 
	default
	esp32_exception_decoder
lib_deps = 
	https://github.com/lewisxhe/TinyGSM-fork.git#6465d529e0bb1552b86c8474de0373bc01da3cc4
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^7.4.2

[web_deps]
lib_deps =
	ayushsharma82/WebSerial@^2.1.1
	ESP32Async/ESPAsyncWebServer@^3.7.10
	ESP32Async/AsyncTCP@^3.4.5

[base_ha]
extends = base
build_flags = 
	${base.build_flags}
	-DHOME_ASSISTANT_INTEGRATION
lib_deps =
	${base.lib_deps}
	${web_deps.lib_deps}

[base_webserial]
extends = base
build_flags = 
	${base.build_flags}
	-DWEB_SERIAL
lib_deps =
	${base.lib_deps}
	${web_deps.lib_deps}

[base_webserial_ha]
extends = base
build_flags = 
	${base.build_flags}
	-DWEB_SERIAL
	-DHOME_ASSISTANT_INTEGRATION
lib_deps =
	${base.lib_deps}
	${web_deps.lib_deps}

[env:debug]
build_type = debug
extends = base
build_flags = 
	${base.build_flags}
	-O0
	-g3
	-fno-omit-frame-pointer
	-DDEBUG
	-Wall
	-Wextra
	-Wno-format-truncation

[env:debugWebSerial]
extends = base_webserial
build_type = debug
build_flags = 
	${base_webserial.build_flags}
	-O0
	-g3
	-fno-omit-frame-pointer
	-DDEBUG
	-Wall
	-Wextra
	-Wno-format-truncation

[env:debugHA]
extends = base_ha
build_type = debug
build_flags = 
	${base_ha.build_flags}
	-O0
	-g3
	-fno-omit-frame-pointer
	-DDEBUG
	-Wall
	-Wextra
	-Wno-format-truncation

[env:debugWebSerialHA]
extends = base_webserial_ha
build_type = debug
build_flags = 
	${base_webserial_ha.build_flags}
	-O0
	-g3
	-fno-omit-frame-pointer
	-DDEBUG
	-Wall
	-Wextra
	-Wno-format-truncation

[env:release]
extends = base
build_flags = 
	${base.build_flags}
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-fno-exceptions
	-DNDEBUG

[env:releaseHA]
extends = base_ha
build_flags = 
	${base_ha.build_flags}
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-fno-exceptions
	-DNDEBUG

[env:releaseWebSerialHA]
extends = base_webserial_ha
build_flags = 
	${base_webserial_ha.build_flags}
	-O2
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-fno-exceptions
	-DNDEBUG
	